### PR TITLE
write_editbox fix 

### PR DESCRIPTION
**Pull request by RobertFewins-Kalb**
not sure why it stopped wrapping text but it is not doing that anymore

### CODE REVIEW

**Comment by theVKC** [comment]
Hmmm. I tested this to the max on 212924… I don’t see the indenting on this one…

**Comment by theVKC** [comment]
NM, just a delay. Also, that was a fake case in case anyone ever audits this.

**Comment by RobertFewins-Kalb** [comment]
You had me sweating for a second...my tests can be seen on training case 211858 in case anyone's interested in catching up on today's news :)

**Comment by theVKC** [comment]
Well, I just tested it with a 27 page case note, and all is well. Other than that the count doesn't go (1 of 8), (2 of 8), etc.

**Comment by RobertFewins-Kalb** [comment]
Unfortunately, the logic isn't there to update (x of y)...but it could be

**Comment by RobertFewins-Kalb** [comment]
Are you trying to awaken the ancient one with that case note?

**Comment by theVKC** [comment]
http://www.lipsum.com/ is your friend.

Don't worry about x of y. Totally unneccessary right now.

**Pull request merged**
