### PR TITLE
creating two SORT function

### PR DESCRIPTION
**Pull request by RobertFewins-Kalb**
BLIP: Creating sort_numeric_array_ascending and sort_numeric_array_descending. The functions will accept, trim, split, and sort numeric arrays, trimming and splitting them as part of the output.

Addresses issue #153

### CODE REVIEW

**Comment by theVKC** [comment]
Does it address #153, or resolve #153? If you use the word "resolves" in your title, it will automatically close the issue when I accept the pull request.

**Comment by RobertFewins-Kalb** [comment]
Resolves #153

**Comment by theVKC** [comment]
@C-Love: why am I thinking we just talked about this subject today? Maybe?

**Comment by C-Love** [comment]
@theVKC We brushed upon this subject today for sure.

**Pull request merged**
