### PR TITLE
Resolves #191 -- Adding functions for income limits

### LINKED ISSUE #191: Enhancement -- Create global constants for values that change each year
This came about because of a need to change the income standards in NOTES >> LEP SPONSOR INCOME... Methinks constants that change on a yearly basis should be stored in FuncLib so we have just one place to go to change important constant values rather than changing the values piecemeal.

I have already updated NOTES >> LEP SPONSOR INCOME (so that's one script that will need its constants swapped) but we should probably also identify other scripts with constants that need to be updated on an annual basis.

### PR DESCRIPTION
**Pull request by RobertFewins-Kalb**
BLIP: Four new functions have been added: three that allow for a single place for income limit determination and one to help script writers to determine cut off dates.

### CODE REVIEW

**Comment by CDPotter** [comment]
@RobertFewins-Kalb We also tacked on the cutoff dates constant to the 191 issue.

**Comment by theVKC** [comment]
@CDPotter, does @RobertFewins-Kalb's recent pull resolve your issues from https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/issues/2123?

**Comment by CDPotter** [comment]
Indeed it does, I asked him to tack on the cutoff date constants.

**Comment by theVKC** [comment]
Good deal. I'll pull his work in before I pull your work in.

**Pull request merged**
